# conexão com o Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/ghiblibox_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# config do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# mostra as queries SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true